### ISSUE TITLE
Integrate Apache Geode and Jetty 11

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-boot-data-geode#116]
_Spring Boot for Apache Geode_ `2.0` is [based on](https://github.com/spring-projects/spring-boot-data-geode/blob/2.0.0-M2/gradle.properties#L12) _Spring Boot_ `3.0`, which [declares and manages](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-dependencies/build.gradle#L670-L676) Eclipse Jetty 11, which is necessary to align with Jakarta EE 9 (see [here](https://www.eclipse.org/jetty/)).

However, Apache Geode `1.14.x` ([here](https://github.com/spring-projects/spring-boot-data-geode/blob/2.0.0-M2/gradle.properties#L3)) is based on Eclipse Jetty 9 ([here](https://github.com/apache/geode/blob/rel/v1.14.4/boms/geode-all-bom/src/test/resources/expected-pom.xml#L424-L429)), which does not match nor align with _Spring Boot_ `3.0` and potentially causes issues for users building _Spring Boot_, Web applications based on the Jakarta EE 9 specification.

This task is to align Apache Geode's **Eclipse Jetty** dependency with _Spring Boot_ `3.0`.

**Comment by jxblum** [comment]
Currently, when Apache Geode `1.14.x` is upgraded to **Eclipse Jetty 11** (in order to match _Spring Boot_ `3.0` and the Jakarta EE 9 specification), then the following log messages is output in the Apache Geode peer `Cache` node's log:

```txt
2022-04-13 21:07:20,782  WARN geode.internal.cache.InternalHttpService:  86 - 
Could not enable HttpService: 'void org.eclipse.jetty.server.SslConnectionFactory.<init>(org.eclipse.jetty.util.ssl.SslContextFactory, java.lang.String)'
```

This log messages is output when Apache Geode's embedded HTTP service (`HttpService`), which is based on **Eclipse Jetty**, is initialized on startup.

Upon closer analysis (debugging), the underlying root cause of the problem is:

```java
java.lang.NoSuchMethodError: 'void org.eclipse.jetty.server.SslConnectionFactory.<init>(org.eclipse.jetty.util.ssl.SslContextFactory, java.lang.String)'
    at org.apache.geode.internal.cache.InternalHttpService.createJettyServer(InternalHttpService.java:131
    at  org.apache.geode.internal.cache.InternalHttpService.init(InternalHttpService.java:81)
    at org.apache.geode.internal.cache.GemFireCacheImpl.initializeServices(GemFireCacheImpl.java:1505)
    at org.apache.geode.internal.cache.GemFireCacheImpl.initialize(GemFireCacheImpl.java:1432)
    at org.apache.geode.internal.cache.InternalCacheBuilder.create(InternalCacheBuilder.java:191)
    at org.apache.geode.internal.cache.InternalCacheBuilder.create(InternalCacheBuilder.java:158)
    at org.apache.geode.cache.CacheFactory.create(CacheFactory.java:142)
    at org.springframework.data.gemfire.CacheFactoryBean.createCache(CacheFactoryBean.java:227)
...
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
    at org.springframework.geode.boot.autoconfigure.cluster.aware.SecureClusterAwareConfigurationIntegrationTests
        $TestGeodeServerConfiguration.main(SecureClusterAwareConfigurationIntegrationTests.java:224)]
```
